import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans antialiased min-h-screen min-w-full ${inter.className}`}
      >
        <div className="flex flex-col min-h-screen min-w-full">
          <Header />
          <div className="flex-1 container max-w-6xl">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
